Merge branch DeviceSettingsApiPUT into dev
mwath/Integration pull request #15
Opened 2021-11-20 19:53 UTC by sebastienvolont

Merge branch DeviceSettingsApiPUT into dev. This adds the features of adding and modifying a device and some global correctings errors / warnings

2021-11-23 23:10 UTC, mwath requested changes
Il y a juste 2-3 trucs à changer et puis c'est bon.
N'oublie pas de formater les fichiers modifiés !

2021-11-23 23:10 UTC, mwath commented on web/src/components/DevicesManagement.tsx
> +class DevicesManagement extends React.Component {
Il manque les types des props/state sur le component.

2021-11-23 23:10 UTC, mwath commented on web/src/components/DevicesManagement.tsx
> +    };
C'est possible de faire ça sans constructeur:
```Typescript
state: TypeState = {
      modalShow: false,
      setModalShow: false,
      validAlertShow: false,
      invalidAlertShow: false,
      setInvalidAlertShow: false,
      setValidAlertShow: false,
      messageErreur: "",
}
```

2021-11-23 23:10 UTC, mwath commented on web/src/components/DevicesManagement.tsx
> +    } else {
indentation ?

2021-11-23 23:10 UTC, mwath commented on web/src/components/DevicesManagement.tsx
> +    } else {
Il faudrait voir pour formater le fichier 🤔

2021-11-23 23:10 UTC, mwath commented on web/src/components/DevicesManagement.tsx
> +          fetch("https://localhost/api/devices" + (isNaN(id) ? "" : `/${id}`), {method: methodParameter,
Il ne faut pas utiliser localhost.
A la place, utilise le chemin absolu: `/api/devices`

2021-11-23 23:10 UTC, mwath commented on web/src/components/FormDeviceOptions.tsx
> +    }
Pareil ici, les types et le constructeur n'est pas nécessaire.

2021-11-23 23:10 UTC, mwath commented on web/src/pages/Details.tsx
>          console.log(typeof (id));
S'ils ne sont plus nécessaire, il faudrait enlever les console.log

2021-11-23 23:10 UTC, mwath commented on web/src/pages/ListDevices.tsx
> +		console.log(devices);
logs

2021-11-23 23:10 UTC, mwath commented on web/src/pages/ListDevices.tsx
> +                        <DeviceBox key={device.id} img={[<BsLamp key={device.id}/>]} name={device.name} state="success" ipAddress={device.ip} groupId={device.groupId} type={device.type} id={device.id
Pourquoi tu mets la propriété `key` à la fois sur l'élément `DeviceBox` et sur l'image `BsLamp` ?

2021-11-23 23:44 UTC, sebastienvolont commented on web/src/pages/ListDevices.tsx
> +                        <DeviceBox key={device.id} img={[<BsLamp key={device.id}/>]} name={device.name} state="success" ipAddress={device.ip} groupId={device.groupId} type={device.type} id={device.id
> Pourquoi tu mets la propriété `key` à la fois sur l'élément `DeviceBox` et sur l'image `BsLamp` ?

J'ai rajouté la propriété ``key`` à l'image ``BsLamp`` qui est un composant react car il me semble que ce composant a besoin d'une clé (``key``) lors de l'utilisation de la fonction map() pour permettre de différencier les différents composants montés d'image ``BsLamp``  pour chaque appareil contenus dans la table "devices" de la base de données.

Sans cette clé, le composant provoquait un « warning » dans la console de développement Chrome.

2021-11-24 13:08 UTC, mwath commented on web/src/components/DevicesManagement.tsx
> +class DevicesManagement extends React.Component {
`React.Component<{}, DevicesManagementInterface>`

2021-11-24 20:14 UTC, mwath approved these changes
Parfait

2021-11-24 20:15 UTC, merged